# Generated by Django 4.2.6 on 2023-10-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_Main',
            field=models.BooleanField(default=False),
        ),
    ]
